[package]
name = "fluxa"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
env_logger = "0.11.6"
log = "0.4.25"
reqwest = { version = "0.12.12", default-features = false, features = [
  "rustls-tls",
] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
