# Pushover API key
pushover_api_key = "api key"
# Pushover user or group key
pushover_user_key = "key"

[[services]]
# Monitored url
url = "http://localhost:3000"
# How ofter the url will be monitored
interval_seconds = 300
# Determin how many times it will try before the url will be considered as down
max_retries = 3
# How many seconds retry has to wait before next try
retry_interval = 3
