# Pushover API key
pushover_api_key = "api key"
# Pushover user or group key
pushover_user_key = "key"

# Service is an array and can be defined multiple times
#
# Example
#
# [[services]]
# url = "https:/rbas.cz"
# interval_seconds = 300
# max_retries = 3
# retry_interval = 3
#
# [[services]]
# url = "https://uptime.kuma.pet/"
# interval_seconds = 300
# max_retries = 3
# retry_interval = 3

[fluxa]
# HTTP server configuration
listen = "127.0.0.1:8080"

# Optional: Unix socket for API access (uncomment to enable)
# api_socket = "/tmp/fluxa.sock"

[[services]]
# Monitored url
url = "http://localhost:3000"
# How often the url will be monitored
interval_seconds = 300
# Determine how many times it will try before the url will be considered as down
max_retries = 3
# How many seconds retry has to wait before next try
retry_interval = 3
